Docs: Deno and React
ripple/ripple-lib pull request #1387
Opened 2021-03-23 06:57 UTC by elmurci

Add information for deno and react se in Readme.

2021-03-31 02:38 UTC, intelliot requested changes

2021-03-31 06:25 UTC, intelliot commented on README.md
> +    npm i --save react-native-crypto
`npm i --save ripple-lib`

2021-03-31 06:35 UTC, intelliot commented
I tried for a while, but I couldn't actually get the React Native instructions to work (trying to use the current version of React Native). Maybe it only worked on a previous version? Can you try it and if it works, let me know which version you used?

2021-03-31 06:55 UTC, elmurci commented on README.md
> +    npm i --save-dev rn-nodeify@latest
That bit is brought from the `rn-nodeify` [instructions](https://github.com/tradle/rn-nodeify)

2021-03-31 08:25 UTC, elmurci commented on README.md
> +    npm i --save react-native-crypto
Changed to `yarn`. Altough we use `yarn` with `ripple-lib`, the user might be using `npm` with their `react-native` app though.

2021-03-31 08:26 UTC, elmurci commented on README.md
> +While official support for [Deno](https://deno.land) is added, you can use the following work-around to use `ripple-lib` with Deno:
Done.

2021-03-31 08:26 UTC, elmurci commented on README.md
> +    ./node_modules/.bin/rn-nodeify --hack --install
You are correct, my bad. Done.

2021-03-31 08:27 UTC, elmurci commented
> I tried for a while, but I couldn't actually get the React Native instructions to work (trying to use the current version of React Native). Maybe it only worked on a previous version? Can you try it and if it works, let me know which version you used?

What error did you get?

I created again a new `react-native` app and followed the steps and it worked.
Did you do `pod install` from the `ios` folder?

2021-03-31 17:33 UTC, mrosendin commented
@intelliot I checked my `package.json` and I had the `stream` package installed:

```
    "stream": "^0.0.2",
```

I think there are additional packages that you will be required to install. I think these steps are missing from the setup instructions and should be included.

It would be ideal if `ripple-lib` was supported natively. From that perspective, adding these additional packages is a drawback of sorts. However, native support of `ripple-lib` seems like a pretty huge effort, as it would require rewriting/rewiring `crypto` and potentially other core modules. All in all what we have here works and that is good enough 👍🏻

2021-03-31 18:32 UTC, intelliot commented
I assume this only works with React Native CLI, and does not work with Expo

2021-04-01 13:20 UTC, elmurci commented
> @intelliot I checked my `package.json` and I had the `stream` package installed:
> 
> ```
>     "stream": "^0.0.2",
> ```
> 
> I think there are additional packages that you will be required to install. I think these steps are missing from the setup instructions and should be included.
> 
> It would be ideal if `ripple-lib` was supported natively. From that perspective, adding these additional packages is a drawback of sorts. However, native support of `ripple-lib` seems like a pretty huge effort, as it would require rewriting/rewiring `crypto` and potentially other core modules. All in all what we have here works and that is good enough 👍🏻

I don't think additional packages need to be explicitly installed.
I was able to send a prepare, sign and send a payment following the instructions above starting a project from scratch.

The one thing I have added is an extra step to explicitly state that the shim file needs to be imported.

If you think there are additional packages needed please share steps to recreate.

2021-04-07 01:03 UTC, intelliot commented
This is the error I'm getting now:
```
 ERROR  TypeError: null is not an object (evaluating 'RNRandomBytes.seed')
```

2021-04-07 03:46 UTC, intelliot commented
> @intelliot I checked my `package.json` and I had the `stream` package installed:
> 
> ```
>     "stream": "^0.0.2",
> ```

If I add "stream" to my package.json then I get these errors:

```
error: Error: Unable to resolve module crypto from /Users/elliot/react/AwesomeProject/node_modules/ripple-lib/dist/npm/common/hashes/sha512Half.js: crypto could not be found within the project or in these directories:
  node_modules/ripple-lib/node_modules
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  1 | "use strict";
  2 | Object.defineProperty(exports, "__esModule", { value: true });
> 3 | const crypto_1 = require("crypto");
    |                           ^
  4 | const sha512Half = (hex) => {
  5 |     return crypto_1.createHash('sha512')
  6 |         .update(Buffer.from(hex, 'hex'))
    at ModuleResolver.resolveDependency (/Users/elliot/react/AwesomeProject/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:234:15)
    at DependencyGraph.resolveDependency (/Users/elliot/react/AwesomeProject/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at Object.resolve (/Users/elliot/react/AwesomeProject/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/Users/elliot/react/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /Users/elliot/react/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/elliot/react/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /Users/elliot/react/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/elliot/react/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
 BUNDLE  ./index.js 

error: Error: Unable to resolve module crypto from /Users/elliot/react/AwesomeProject/node_modules/ripple-lib/dist/npm/common/hashes/sha512Half.js: crypto could not be found within the project or in these directories:
  node_modules/ripple-lib/node_modules
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  1 | "use strict";
  2 | Object.defineProperty(exports, "__esModule", { value: true });
> 3 | const crypto_1 = require("crypto");
    |                           ^
  4 | const sha512Half = (hex) => {
  5 |     return crypto_1.createHash('sha512')
  6 |         .update(Buffer.from(hex, 'hex'))
    at ModuleResolver.resolveDependency (/Users/elliot/react/AwesomeProject/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:234:15)
    at DependencyGraph.resolveDependency (/Users/elliot/react/AwesomeProject/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at Object.resolve (/Users/elliot/react/AwesomeProject/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/Users/elliot/react/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /Users/elliot/react/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/elliot/react/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /Users/elliot/react/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/elliot/react/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
 BUNDLE  ./index.js 

error: Error: Unable to resolve module crypto from /Users/elliot/react/AwesomeProject/node_modules/ripple-lib/dist/npm/common/hashes/sha512Half.js: crypto could not be found within the project or in these directories:
  node_modules/ripple-lib/node_modules
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  1 | "use strict";
  2 | Object.defineProperty(exports, "__esModule", { value: true });
> 3 | const crypto_1 = require("crypto");
    |                           ^
  4 | const sha512Half = (hex) => {
  5 |     return crypto_1.createHash('sha512')
  6 |         .update(Buffer.from(hex, 'hex'))
    at ModuleResolver.resolveDependency (/Users/elliot/react/AwesomeProject/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:234:15)
    at DependencyGraph.resolveDependency (/Users/elliot/react/AwesomeProject/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at Object.resolve (/Users/elliot/react/AwesomeProject/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/Users/elliot/react/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /Users/elliot/react/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/elliot/react/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /Users/elliot/react/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/elliot/react/AwesomeProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
```

2021-04-07 05:03 UTC, mrosendin commented
@intelliot you probably need to run the `rn-nodeify --hack` command again. I basically run it every time I add a new package.

2021-04-07 06:20 UTC, intelliot commented
@mrosendin thanks for the reply, but even after running that, I'm still getting the error:
```
 ERROR  TypeError: null is not an object (evaluating 'RNRandomBytes.seed')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

If you happen to have time, do you see any issue with my project? Maybe it's a problem with my dev environment... https://github.com/intelliot/react-native-ripple-lib

2021-04-07 06:26 UTC, mrosendin commented
The linked project issues were resolved by modifying the Podfile. Here's a summary of what I did:

> Steps taken with the example proj with Node v14.15.3

- `yarn`
- `cd ios && rm Podfile.lock && pod install`
- run `./node_modules/rn-nodeify --hack --install`
- `npx react-native run-ios` (I'm using `npx` here instead of the RN CLI)
- saw `duplicate symbols for architecture x86_64` in the build errors. problem seems to be with `react-native-udp` being doubly linked. after a bit of debugging I saw that Flipper was enabled in `Podfile`. I commented it out:

```
  # Uncomment the code below to enable Flipper.
  #
  # You should not install Flipper in CI environments when creating release
  # builds, this will lead to significantly slower build times.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work.
  #
  #  use_flipper!
  #  post_install do |installer|
  #    flipper_post_install(installer)
  #  end
```

- run `cd ios && rm Podfile.lock && pod install` again
- `npx react-native run-ios`

Got an error this time about TCP sockets:

```
❌  duplicate symbol '_GCDAsyncSocketUseCFStreamForTLS' in
> libCocoaAsyncSocket.a(GCDAsyncSocket.o)
> libTcpSockets.a(GCDAsyncSocket.o)
```

**Podfile**

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'AwesomeProject' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'AwesomeProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  # post_install do |installer|
  #   react_native_post_install(installer)
  # end
end
```

I just saw https://github.com/Rapsssito/react-native-tcp-socket/issues/36 and https://github.com/Rapsssito/react-native-tcp-socket/issues/61 which lead me to believe that it's best solved from within xCode itself. I will try to investigate further tomorrow.

2021-04-07 06:34 UTC, mrosendin commented
Nvm, I thought I could just try in xCode really quickly and the build succeeded! Follow the solution [here](https://github.com/Rapsssito/react-native-tcp-socket/issues/61) but replace `CocoaAsyncSocket ` with `GCDAsyncSocket`.

2021-04-07 07:21 UTC, elmurci commented
> @mrosendin thanks for the reply, but even after running that, I'm still getting the error:
> 
> ```
>  ERROR  TypeError: null is not an object (evaluating 'RNRandomBytes.seed')
>  ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
>       This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
>  ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
>       This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
> ```
> 
> If you happen to have time, do you see any issue with my project? Maybe it's a problem with my dev environment... https://github.com/intelliot/react-native-ripple-lib

@intelliot I was able to run your project with no issues (after fixing the `GCDAsyncSocket` problem as @mrosendin pointed out)

2021-04-08 23:14 UTC, intelliot approved these changes

2021-04-09 05:30 UTC, merged