Renames RippleAPI client to XrplClient
ripple/ripple-lib pull request #1520
Opened 2021-08-10 23:56 UTC by mvadari

## High Level Overview of Change

### Context of Change

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

## Before / After

## Test Plan

2021-08-11 00:37 UTC, mvadari commented on test/api/constructor/index.ts
> -import {RippleAPI} from 'ripple-api'
These files were just moved to `test/client`, not deleted - I think git had a hard time with the diff

2021-08-11 03:45 UTC, intelliot commented
I would be tempted to rename it `XRPL` because it's shorter and `Xrpl` looks like strange capitalization to me

2021-08-11 15:38 UTC, mvadari commented
@intelliot are you suggesting renaming it to `XRPLClient` or just `XRPL`?

2021-08-11 20:25 UTC, khancode commented
How are we handling code breaking for users of xrpl.js when this change is released? Do we expect users to read v2.0 docs to use `XrplClient` instead of `RippleAPI`?

2021-08-11 20:27 UTC, mvadari commented
We're going to write up docs for how to make the upgrade and navigate the breaking changes. `RippleAPI` will no longer exist, and is being replaced by `XrplClient`.

2021-08-12 16:42 UTC, intelliot commented
> @intelliot are you suggesting renaming it to `XRPLClient` or just `XRPL`?

Just `XRPL`.

2021-08-16 17:38 UTC, mvadari commented
After discussing with @natenichols and @ledhed2222, I'm changing the name to `Client`.

2021-08-16 23:13 UTC, intelliot approved these changes

2021-08-17 00:24 UTC, natenichols commented on scripts/ci.sh
> +  ln -nfs ../../dist/npm test-compiled/node_modules/xrpl-client
Do we use `ci.sh` anymore?

2021-08-17 00:28 UTC, natenichols commented on test/client/getTransactions/index.ts
> +import {Client} from 'xrpl-client'
xrpl-client is already taken on `npm.js`, I think we'll want this to be either `xrpl` or `xrpl-js`

2021-08-17 00:32 UTC, natenichols requested changes
I don't think we can call it `xrpl-client`, that's already taken by [XRPL Labs](https://www.npmjs.com/package/xrpl-client) websocket client library.

I like `xrpl-js` or `XRPL`

2021-08-17 04:50 UTC, intelliot commented
The npm package name will be `xrpl`, similar to how the package for web3.js is `web3`. I've reserved the name.

`xrpl-client` in this PR is a rename of `ripple-api` which is just an [internal symlink (symbolic link)](https://github.com/ripple/ripple-lib/blob/develop/test/node_modules/ripple-api) to the [src directory](https://github.com/ripple/ripple-lib/tree/develop/src). Due to how imports work, this effectively points to [`./src/index.ts`](https://github.com/ripple/ripple-lib/blob/develop/src/index.ts). It's not related to the npm package name.

So I think this PR is ok as-is. I think renaming `xrpl-client` to `xrpl-local-working-copy` (or similar) would be more accurate / less confusing, but it's not a big deal and shouldn't affect the external API.

2021-08-17 15:56 UTC, mvadari commented
I renamed it to `xrpl-local` to make it a little more clear

2021-08-17 18:08 UTC, natenichols approved these changes

2021-08-17 18:16 UTC, merged