refactor: Define EscrowFinish Transaction
ripple/ripple-lib pull request #1531
Opened 2021-08-16 19:34 UTC by natenichols

## High Level Overview of Change
Defines `EscrowFinish` Transaction type

### Context of Change
Add `EscrowFinish` TypeScript definition, `verifyEscrowFinish` functionality,  and tests for `verifyEscrowFinish`

### Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

2021-08-18 00:25 UTC, mvadari approved these changes

2021-08-18 20:16 UTC, mukulljangid approved these changes
LGTM

2021-08-18 20:16 UTC, mukulljangid commented on src/models/transactions/escrowFinish.ts
> +    Fulfillment?: string;
remove the semicolons and you're good to go!

2021-08-18 20:16 UTC, mukulljangid commented on src/models/transactions/transaction.ts
> +import { EscrowFinish } from "./escrowFinish";
ditto

2021-08-18 22:29 UTC, khancode requested changes
Suggesting the same changes to be made just like with [EscrowCancel PR](https://github.com/ripple/ripple-lib/pull/1511#pullrequestreview-733379253):
- make tests easier to write/read (using beforeEach())
- make error messages more concise
- nit: remove semicolons

2021-08-19 15:13 UTC, khancode approved these changes
LGTM!

2021-08-19 15:58 UTC, merged