refactor: Define PaymentChannelFund transaction model
ripple/ripple-lib pull request #1535
Opened 2021-08-16 22:51 UTC by natenichols

## High Level Overview of Change
Defines PaymentChannelFund transaction model.

### Context of Change
Defines a typescript type for `PaymentChannelFund`, `verifyPaymentChannelFund()` for verifying Transaction form at runtime, and tests for `verifyPaymentChannelFund`.

### Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

2021-08-18 22:26 UTC, JST5000 commented on test/models/paymentChannelFund.ts
> +    it (`throws w/ missing Channel`, () => {
This should probably be 'throws with invalid Channel' since there is a Channel defined, it's just the wrong format.

2021-08-18 22:28 UTC, JST5000 requested changes
One small change

2021-08-18 22:34 UTC, khancode requested changes
Suggesting the same changes to be made just like with [EscrowCancel PR](https://github.com/ripple/ripple-lib/pull/1511#pullrequestreview-733379253):
- make tests easier to write/read (using beforeEach())
- make error messages more concise
- nit: remove semicolons

2021-08-19 15:43 UTC, khancode approved these changes
LGTM!

2021-08-19 16:03 UTC, mvadari approved these changes

2021-08-19 16:09 UTC, JST5000 approved these changes
LTGM!

2021-08-19 16:21 UTC, merged