refactor: define typescript type for AccountDelete transaction
ripple/ripple-lib pull request #1537
Opened 2021-08-17 15:10 UTC by mukulljangid

## High Level Overview of Change
Defines typescript types for AccountDelete transaction.

### Context of Change
AccountDelete is an extension of CommonFields, and is exported in a type union with all other transaction types defined as Transaction.

We also will provide an optional verifyAccountDelete function for runtime form checking of AccountDelete transactions, should the users want to verify transaction form at runtime.

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

## Test Plan
Adds tests for verifyAccountDelete, which provides runtime form verification for AccountDelete transactions

2021-08-17 16:59 UTC, mvadari commented on src/models/transactions/accountDelete.ts
> +        throw new ValidationError("AccountDelete: invalid DestinationTag")
Check the fee too - it should be 5 XRP

2021-08-17 19:04 UTC, mukulljangid commented on src/models/transactions/accountDelete.ts
> +        throw new ValidationError("AccountDelete: invalid DestinationTag")
Done!

2021-08-18 17:55 UTC, natenichols commented on src/models/transactions/accountDelete.ts
> +    Destination: string;
I think we can add `Fee: 5` to this typescript definition. Fee should always be 5 in `AccountDelete` Transactions IIRC.

2021-08-18 17:56 UTC, natenichols approved these changes
Left one comment, nothing to hold up approval, though. LGTM 👍 

Just make sure you add that `Fee: 5`

2021-08-18 17:58 UTC, intelliot requested changes
The fee can change based on a vote of the validators. We should at least explore/consider the possibility of retrieving the current owner reserve from rippled and using that as the fee.

2021-08-18 17:59 UTC, intelliot approved these changes
Actually, I'm fine with removing the check from the model. We should consider a preflight check in the client, as well as ensuring that autofill does the right thing.

2021-08-18 18:54 UTC, merged